function [Time1, Distance1, IDC1, UDC1] = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [TIME1, DISTANCE1, IDC1, UDC1] = IMPORTFILE1(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [TIME1, DISTANCE1, IDC1, UDC1] = IMPORTFILE1(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Time1, Distance1, IDC1, UDC1] = importfile1("C:\Users\Roland Kummer\Documents\Studium\BA-Arbeit\210721_zenzenhof.csv", [4764, 12296]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Mar-2022 12:20:48

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4764, 12296];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time1", "Distance1", "IDC1", "UDC1"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time1 = tbl.Time1;
Distance1 = tbl.Distance1;
IDC1 = tbl.IDC1;
UDC1 = tbl.UDC1;
end